sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  include:
    - os: linux
      arch: arm64
      python: 3.6
install:
  - "pip install 'virtualenv<14.0.0' tox"
script: tox -e py
